In [103]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import KNeighborsClassifier # El KNN
from sklearn.preprocessing import StandardScaler, MinMaxScaler

from sklearn.metrics import r2_score

In [77]:
# Nos traemos la base de datos:
df = pd.read_csv('./Diamonds-Prices2022.csv')
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [78]:
df.drop('Unnamed: 0', axis=1, inplace=True)

In [79]:
X = df.drop('price', axis=1)
y = df['price']

In [80]:
X.head()

   carat      cut color clarity  depth  table     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0  4.34  4.35  2.75

In [81]:
y.head()

0    326
1    326
2    327
3    334
4    335
Name: price, dtype: int64

In [82]:
encoder = LabelEncoder()

X_encoded = X.copy()

In [83]:

for column in X_encoded[ ['cut', 'color', 'clarity'] ]:
    print(f'Columna {column}, variables: {list(X_encoded[column].unique())}')

Columna cut, variables: ['Ideal', 'Premium', 'Good', 'Very Good', 'Fair']
Columna color, variables: ['E', 'I', 'J', 'H', 'F', 'G', 'D']
Columna clarity, variables: ['SI2', 'SI1', 'VS1', 'VS2', 'VVS2', 'VVS1', 'I1', 'IF']

In [84]:
for column in X[ ['cut', 'color', 'clarity'] ]:
    X_encoded[column] = encoder.fit_transform(X_encoded[column])

In [85]:
X_encoded.head()

   carat  cut  color  clarity  depth  table     x     y     z
0   0.23    2      1        3   61.5   55.0  3.95  3.98  2.43
1   0.21    3      1        2   59.8   61.0  3.89  3.84  2.31
2   0.23    1      1        4   56.9   65.0  4.05  4.07  2.31
3   0.29    3      5        5   62.4   58.0  4.20  4.23  2.63
4   0.31    1      6        3   63.3   58.0  4.34  4.35  2.75

In [86]:
X_encoded.isna().sum()

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
x          0
y          0
z          0
dtype: int64

In [87]:
X_encoded.dtypes, X_encoded.head()

(carat      float64
 cut          int64
 color        int64
 clarity      int64
 depth      float64
 table      float64
 x          float64
 y          float64
 z          float64
 dtype: object,
    carat  cut  color  clarity  depth  table     x     y     z
 0   0.23    2      1        3   61.5   55.0  3.95  3.98  2.43
 1   0.21    3      1        2   59.8   61.0  3.89  3.84  2.31
 2   0.23    1      1        4   56.9   65.0  4.05  4.07  2.31
 3   0.29    3      5        5   62.4   58.0  4.20  4.23  2.63
 4   0.31    1      6        3   63.3   58.0  4.34  4.35  2.75)

In [88]:
for column in X_encoded[ ['cut', 'color', 'clarity'] ]:
    print(f'Columna {column}, variables: {X_encoded[column].unique()}')

Columna cut, variables: [2 3 1 4 0]
Columna color, variables: [1 5 6 4 2 3 0]
Columna clarity, variables: [3 2 4 5 7 6 0 1]

In [89]:
X_encoded.describe().loc[['mean','std','min','max']]

,carat,cut,color,clarity,depth,table,x,y,z
mean,0.797935,2.553047,2.594127,3.835104,61.749322,57.457251,5.731158,5.734526,3.538730
std,0.473999,1.027702,1.701087,1.724587,1.432626,2.234549,1.121730,1.142103,0.705679
min,0.200000,0.000000,0.000000,0.000000,43.000000,43.000000,0.000000,0.000000,0.000000
max,5.010000,4.000000,6.000000,7.000000,79.000000,95.000000,10.740000,58.900000,31.800000

In [90]:
y.shape

(53943,)

In [91]:
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded, y, test_size=0.25, random_state=42
)

In [92]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)  
X_test_scaled = scaler.transform(X_test)

In [95]:
arbol_decision = DecisionTreeClassifier(max_depth=7)

In [96]:
arbol_decision.fit(X_train_scaled, y_train)

DecisionTreeClassifier(max_depth=7)

In [97]:
arbol_decision.score(X_test_scaled, y_test)

0.04004152454397153

In [100]:
model_lr = LinearRegression()
model_lr.fit(X_train_scaled, y_train)

LinearRegression()

In [101]:
# Predicciones
y_predlr = model_lr.predict(X_test_scaled)

In [102]:
y_predlr

array([ 361.98451602, 8009.98359175,  157.21709295, ..., 5238.48399369,
       5135.11149967, 1976.68304732], shape=(13486,))

In [105]:
r2 = r2_score(y_test, y_predlr)
r2

0.888166762266777